version: '3.8'

services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: